export const APP_ACTION_CONST = {
  LOADING_TRUE: 'APP/LOADING_TRUE',
  LOADING_FALSE: 'APP/LOADING_FALSE',
  ERROR: 'ERROR',
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  ADD_CATEGORY_ITEM: 'ADD_CATEGORY_ITEM',
  UPDATE_CATEGORY_ITEM: 'UPDATE_CATEGORY_ITEM',
  REMOVE_CATEGORY_ITEM: 'REMOVE_CATEGORY_ITEM',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  ADD_PRODUCT_ITEM: 'ADD_PRODUCT_ITEM',
  UPDATE_PRODUCT_ITEM: 'UPDATE_PRODUCT_ITEM',
  REMOVE_PRODUCT_ITEM: 'REMOVE_PRODUCT_ITEM',
}
